# Laborator 6

Versiunea 2020-04-01

## Modele de clasificare

Folositi 4 seturi de date pentru probleme de clasificare, plecand de la repository-urile specificate in Cursul 5; de exemplu, [ics.uci.edu](http://archive.ics.uci.edu/ml/datasets.php?format=mat&task=cla&att=&area=&numAtt=&numIns=&type=mvar&sort=nameUp&view=table). Cel putin doua seturi de date sa fie cu valori lipsa. 


1. (20 puncte) Aplicati o metoda de missing value imputation, unde este cazul; justificati si documentati metoda folosita.
1. (numar de modele * numar de seturi de date \* 1 punct = 20 de puncte) Pentru fiecare set de date aplicati 5 modele de clasificare din scikit learn. Pentru fiecare raportati: acuratete, scorul F1 - a se vedea [sklearn.metrics](http://scikit-learn.org/stable/modules/classes.html#module-sklearn.metrics) - folosind 5 fold cross validation. Raportati mediile rezultatelor atat pentru fold-urile de antrenare, cat si pentru cele de testare. Rularile se vor face cu valori fixate ale hiperparametrilor. 
1. (numar modele * 4 puncte = 20 puncte) Documentati in jupyter notebook fiecare din modelele folosite, in limba romana. Daca acelasi algoritm e folosit pentru mai multe seturi de date, puteti face o sectiune separata cu documentarea algoritmilor + trimitere la algoritm. 
1. (numar de modele * numar de seturi de date * 1 punct = 20 de puncte) Raportati performanta fiecarui model, folosind 5 fold cross validation. Pentru fiecare din cele 5 rulari, cautati hiperparametrii optimi folosind 4-fold cross validation. Performanta modelului va fi raportata ca medie a celor  5 rulari. 
    *Observatie:* la fiecare din cele 5 rulari, hiperparametrii optimi pot diferi, din cauza datelor utilizate pentru antrenare/validare. 

Se acorda 20 de puncte din oficiu. 

Exemple de modele de clasificare:
1. [Multi-layer Perceptron classifier](https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html#sklearn.neural_network.MLPClassifier)
1. [KNN](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html#sklearn.neighbors.KNeighborsClassifier)
1. [SVM](https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html#sklearn.svm.SVC)
1. [Gaussian processes](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessClassifier.html#sklearn.gaussian_process.GaussianProcessClassifier)
1. [RBF](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.kernels.RBF.html#sklearn.gaussian_process.kernels.RBF)
1. [Decision tree](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html#sklearn.tree.DecisionTreeClassifier)
1. [Random forest](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier)
1. [Gaussian Naive bayes](https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.GaussianNB.html#sklearn.naive_bayes.GaussianNB) 

In [15]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

print ('numpy:', np.__version__)
print ('pandas:', pd.__version__)

import sklearn
from sklearn.metrics import accuracy_score

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.gaussian_process.kernels import RBF, ConstantKernel as C
from sklearn import metrics
from sklearn.model_selection import cross_val_score
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier

numpy: 1.18.1
pandas: 1.0.1


### 1. Missing value imputation

### 2. Accuracy and F1 score

### Wine Data Set
#### (http://archive.ics.uci.edu/ml/datasets/Wine)

### KNN

#### Load data

In [2]:
wine_data = pd.read_csv('D:\Projects\Facultate\II\II_Sem_2_10_REPOS\IDS\Lab6\Data\Wine\wine.data', header=None)
wine_data.head()

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

#### Interpret data

In [3]:
X_Wine = wine_data.values[:, 1:]
y_Wine = wine_data.values[:, 0] #prima coloana reprezinta ground truth

#### Split data

In [4]:
test_size = 1/3
X_Wine_train, X_Wine_test, y_Wine_train, y_Wine_test = train_test_split(X_Wine, y_Wine, test_size=test_size, random_state=5)

#### Fit data

In [5]:
model_KNN_Wine = KNeighborsClassifier(n_neighbors=5)
model_KNN_Wine.fit(X_Wine_train, y_Wine_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

#### Accuracy

In [6]:
y_Wine_h = model_KNN_Wine.predict(X_Wine_test)
accuracy_KNN_Wine = accuracy_score(y_Wine_test, y_Wine_h)

print(f'Accuracy (KNN): {accuracy_KNN_Wine}')

Accuracy (KNN): 0.7333333333333333


#### Accuracy and F1 score using 5-fold cross validation

In [7]:
cv = 5

In [8]:
#Accuracy (5-fold)
score_KNN_Wine_accuracy = cross_val_score(model_KNN_Wine, X_Wine, y_Wine, cv=cv, scoring='accuracy')
print(f'Accuracy (KNN, 5-fold cv):\n {score_KNN_Wine_accuracy}')
mean_score_KNN_Wine_accuracy = score_KNN_Wine_accuracy.mean()
print(f'Accuracy (KNN, 5-fold cv, mean): {mean_score_KNN_Wine_accuracy}')

Accuracy (KNN, 5-fold cv):
 [0.72222222 0.66666667 0.63888889 0.65714286 0.77142857]
Accuracy (KNN, 5-fold cv, mean): 0.6912698412698413


In [9]:
#F1 score (5-fold)
score_KNN_Wine_f1 = metrics.f1_score(y_Wine_test, y_Wine_h, average='weighted')
print(f'F1 score (KNN, 5-fold cv):\n {score_KNN_Wine_f1}')

F1 score (KNN, 5-fold cv):
 0.7311348929815829


In [10]:
#Accuracy (5-fold) for training and test set
score_KNN_Wine_accuracy_train = cross_val_score(model_KNN_Wine, X_Wine_train, y_Wine_train, cv=cv, scoring='accuracy')
print(f'Accuracy (KNN, 5-fold cv, train):\n {score_KNN_Wine_accuracy_train}')

mean_score_KNN_Wine_accuracy_train = score_KNN_Wine_accuracy_train.mean()
print(f'Accuracy (KNN, 5-fold cv, train, mean): {mean_score_KNN_Wine_accuracy_train}')

print()

score_KNN_Wine_accuracy_test = cross_val_score(model_KNN_Wine, X_Wine_test, y_Wine_test, cv=cv, scoring='accuracy')
print(f'Accuracy (KNN, 5-fold cv, test):\n {score_KNN_Wine_accuracy_test}')

mean_score_KNN_Wine_accuracy_test = score_KNN_Wine_accuracy_test.mean()
print(f'Accuracy (KNN, 5-fold cv, test, mean): {mean_score_KNN_Wine_accuracy_test}')

Accuracy (KNN, 5-fold cv, train):
 [0.41666667 0.66666667 0.625      0.65217391 0.73913043]
Accuracy (KNN, 5-fold cv, train, mean): 0.619927536231884

Accuracy (KNN, 5-fold cv, test):
 [0.66666667 0.66666667 0.58333333 0.83333333 0.75      ]
Accuracy (KNN, 5-fold cv, test, mean): 0.7


In [11]:
#F1 score (5-fold) for training and test set
score_KNN_Wine_f1_train = cross_val_score(model_KNN_Wine, X_Wine_train, y_Wine_train, cv=cv, scoring='f1_macro')
print(f'F1 score (KNN, 5-fold cv, train):\n {score_KNN_Wine_f1_train}')

mean_score_KNN_Wine_f1_train = score_KNN_Wine_f1_train.mean()
print(f'F1 score (KNN, 5-fold cv, train, mean): {mean_score_KNN_Wine_f1_train}')

print()

score_KNN_Wine_f1_test = cross_val_score(model_KNN_Wine, X_Wine_test, y_Wine_test, cv=cv, scoring='f1_macro')
print(f'F1 score (KNN, 5-fold cv, test):\n {score_KNN_Wine_f1_test}')

mean_score_KNN_Wine_f1_test = score_KNN_Wine_f1_test.mean()
print(f'F1 score (KNN, 5-fold cv, test, mean): {mean_score_KNN_Wine_f1_test}')

F1 score (KNN, 5-fold cv, train):
 [0.45418895 0.60966184 0.60277778 0.6234051  0.71909888]
F1 score (KNN, 5-fold cv, train, mean): 0.601826509814799

F1 score (KNN, 5-fold cv, test):
 [0.6030303  0.62575758 0.55988456 0.76666667 0.6962963 ]
F1 score (KNN, 5-fold cv, test, mean): 0.6503270803270802


#### Hyperparameter search

In [12]:
cv = 5
cv_4 = 4
scoring_acc = 'accuracy'
scoring_f1 = 'f1_score'

In [13]:
parameter_grid = {'n_neighbors': list(range(1, 10)), 'p': [1, 2, 3, 4.7]}

def hyper_KNN(X_train, y_train, X_test, y_test, X, y) -> None:
    
    """
    :param X: matricea de intrare
    :param y: ground truth
    """
    
    #initializam modelul de clasificare
    model = KNeighborsClassifier()
    
    #initializam GridSearchCV pentru a putea face 5-fold cross validation pe modelul KNN
#     grid_search = GridSearchCV(estimator = model, 
#                                param_grid = parameter_grid, 
#                                scoring = scoring, 
#                                cv = cv, 
#                                return_train_score = True) #se foloseste pentru cv_results_ de mai jos
    
#     #antrenare pe setul de antrenare
#     grid_search.fit(X_train, y_train)

#     #dupa antrenare, se face o predictie folosind setul de testare
#     y_estimated = grid_search.predict(X_test)
    
#     df_grid_search = pd.DataFrame(grid_search.cv_results_)
#     df_grid_search.info()
#     df_grid_search.head()
    
#     acc_score = accuracy_score(y_test, y_estimated)
#     print(f'accuracy_score(y_test, y_estimated): {acc_score}') 
    
#     best_params = grid_search.best_params_
#     print(f'Best parameters: {best_params}')
    
    print("--------------------")
    print("5 over 4-fold cross validation (nested cross validation)")
    
    #5 over 4-fold cross validation
    grid_search_5cv = GridSearchCV(estimator = model, 
                                   param_grid = parameter_grid, 
                                   scoring = scoring_acc, 
                                   cv = cv,
                                   return_train_score = True)
    

    #la fiecare rulare din 5-fold se face un 4-fold cross validation
    scores = cross_val_score(grid_search_5cv, X, y, cv = cv_4)
    
    print(f'Scores for 4-fold cross validation:\n {scores}')
    print(f'Mean score for 4-fold cross validation: {scores.mean()}')
    
    grid_search_5cv.fit(X_train, y_train)
    y_estimated = grid_search_5cv.predict(X_test)
    
    best_params = grid_search_5cv.best_params_
    print(f'Best parameters: {best_params}')

In [14]:
hyper_KNN(X_Wine_train, y_Wine_train, X_Wine_test, y_Wine_test, X_Wine, y_Wine)

--------------------
5 over 4-fold cross validation
Scores for 4-fold cross validation:
 [0.71111111 0.8        0.75       0.72727273]
Mean score for 4-fold cross validation: 0.7470959595959596
Best parameters: {'n_neighbors': 1, 'p': 1}


### 3. Documentation

### 4. Hyperparameter search